version: '3.8'

services:
  # app:
  #   build: .
  #   container_name: strimemu
  #   depends_on:
  #     - mongodb
  #     - redis # Добавляем зависимость
  #   command: >
  #     ./main --start_url https://golang.org --max_depth 1
  #   restart: on-failure

  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  mongodb_data: