// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Parser is an autogenerated mock type for the Parser type
type Parser struct {
	mock.Mock
}

// ParseLinks provides a mock function with given fields: baseRawURL, htmlBody
func (_m *Parser) ParseLinks(baseRawURL string, htmlBody []byte) ([]string, error) {
	ret := _m.Called(baseRawURL, htmlBody)

	if len(ret) == 0 {
		panic("no return value specified for ParseLinks")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(string, []byte) ([]string, error)); ok {
		return rf(baseRawURL, htmlBody)
	}
	if rf, ok := ret.Get(0).(func(string, []byte) []string); ok {
		r0 = rf(baseRawURL, htmlBody)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(string, []byte) error); ok {
		r1 = rf(baseRawURL, htmlBody)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewParser creates a new instance of Parser. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewParser(t interface {
	mock.TestingT
	Cleanup(func())
}) *Parser {
	mock := &Parser{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
