# Настройки веб-краулера
start_url: "https://ru.wikipedia.org/wiki/Android" 
same_host: true
max_depth: 1
worker_count: 30

# Настройки HTTP клиента
http:
  timeout: 30s

# Настройки подключения к базе данных MongoDB
mongo:
  uri: "mongodb://root:example@localhost:27017" 
  database: "crawler_db"
  collection: "links"

# Настройки состояния посещенных URL в Redis
redis:
  addr: "localhost:6379"
  password: "" 
  db: 0 
  set_key: "crawler:visited_urls" 

# Настройки логирования
log:
  level: "info" # Возможные значения: debug, info, warn, error